# Generated by Django 4.2.28 on 2026-02-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0121_worklog"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="worklog",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("deleted_at__isnull", True),
                    ("duration", 0),
                ),
                fields=("actor", "issue"),
                name="worklog_unique_active_timer_per_actor_issue",
            ),
        ),
    ]
