# Generated by Django 4.2.29 on 2026-03-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0122_worklog_unique_active_timer_per_actor_issue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="provider",
            field=models.CharField(
                choices=[
                    ("google", "Google"),
                    ("github", "Github"),
                    ("gitlab", "GitLab"),
                ],
                max_length=20,
            ),
        ),
    ]
