# Generated by Django 4.2.28 on 2026-03-17 10:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0123_alter_account_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="recurrence_generated_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="issue",
            name="recurrence_last_run_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="issue",
            name="recurrence_max_occurrences",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="recurrence_next_run_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="issue",
            name="recurrence_pattern",
            field=models.CharField(
                blank=True,
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("bi_weekly", "Bi-weekly"),
                    ("monthly", "Monthly"),
                    ("yearly", "Yearly"),
                    ("every_minute", "Every minute"),
                    ("once", "Once-off"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="recurrence_source_issue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_recurrence_issues",
                to="db.issue",
            ),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(fields=["recurrence_next_run_at"], name="issue_recur_next_run_idx"),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                condition=models.Q(
                    ("recurrence_pattern__isnull", False),
                    ("recurrence_source_issue__isnull", True),
                    ("deleted_at__isnull", True),
                    ("archived_at__isnull", True),
                ),
                fields=["recurrence_next_run_at"],
                name="issue_recur_active_source_idx",
            ),
        ),
    ]
