# Generated by Django 4.2.28 on 2026-03-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0124_issue_recurrence_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='auto_create_cycles',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='auto_transfer_cycle_issues',
            field=models.BooleanField(default=False),
        ),
    ]
