# Generated by Django 4.2.28 on 2026-03-31 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0121_alter_estimate_type'),
        ('db', '0125_add_cycle_automation_fields_to_project'),
    ]

    operations = [
    ]
