# Generated by Django 4.2.28 on 2026-05-27

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.db.models import Q


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0126_merge_20260331_0336"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentConfiguration",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(db_index=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("provider", models.CharField(default="openai", max_length=50)),
                ("api_key_encrypted", models.TextField(blank=True, default="")),
                ("model", models.CharField(default="gpt-4o-mini", max_length=100)),
                ("max_steps", models.PositiveSmallIntegerField(default=10)),
                ("reasoning_level", models.CharField(default="medium", max_length=20)),
                ("is_enabled", models.BooleanField(default=True)),
                ("system_prompt", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_configurations",
                        to="db.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_configurations",
                        to="db.workspace",
                    ),
                ),
            ],
            options={"db_table": "agent_configurations"},
        ),
        migrations.CreateModel(
            name="AgentChatSession",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(db_index=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("selected_model", models.CharField(blank=True, default="", max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_sessions",
                        to="db.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="agent_sessions", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "workspace",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="agent_sessions", to="db.workspace"),
                ),
            ],
            options={"db_table": "agent_chat_sessions", "ordering": ("-created_at",)},
        ),
        migrations.CreateModel(
            name="AgentChatMessage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(db_index=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("role", models.CharField(choices=[("user", "User"), ("assistant", "Assistant"), ("tool", "Tool")], max_length=20)),
                ("content", models.TextField(blank=True, default="")),
                ("tool_calls", models.JSONField(blank=True, null=True)),
                ("tool_call_id", models.CharField(blank=True, default="", max_length=255)),
                ("tool_name", models.CharField(blank=True, default="", max_length=100)),
                ("tool_input", models.JSONField(blank=True, null=True)),
                ("tool_output", models.JSONField(blank=True, null=True)),
                ("model_used", models.CharField(blank=True, default="", max_length=100)),
                ("tokens_sent", models.PositiveIntegerField(default=0)),
                ("tokens_received", models.PositiveIntegerField(default=0)),
                ("reasoning_tokens", models.PositiveIntegerField(default=0)),
                ("step_index", models.PositiveSmallIntegerField(default=0)),
                ("latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("is_error", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="db.agentchatsession"),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "agent_chat_messages", "ordering": ("created_at",)},
        ),
        migrations.AddIndex(
            model_name="agentchatmessage",
            index=models.Index(fields=["session", "created_at"], name="agent_chat_m_session_e1f677_idx"),
        ),
        migrations.AddConstraint(
            model_name="agentconfiguration",
            constraint=models.UniqueConstraint(
                condition=Q(("project__isnull", True)),
                fields=("workspace",),
                name="agent_config_unique_workspace_when_no_project",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="agentconfiguration",
            unique_together={("workspace", "project")},
        ),
    ]
