# Generated by Django 6.0.6 on 2026-08-22 13:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0122_alter_draftissue_assignees_alter_issue_assignees_and_more"),
        ("db", "0130_user_mfa"),
    ]

    operations = []
