# Generated by Django 6.0.6 on 2026-08-22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0131_merge_20260822_1320"),
        ("db", "0132_sync_production_model_state"),
    ]

    operations = []
