// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window["go"]["main"]["App"]["GetConfig"]();
}

export function GetAuthState() {
  return window["go"]["main"]["App"]["GetAuthState"]();
}

export function IsAuthenticated() {
  return window["go"]["main"]["App"]["IsAuthenticated"]();
}

export function OpenLogin() {
  return window["go"]["main"]["App"]["OpenLogin"]();
}

export function GetLoginURL() {
  return window["go"]["main"]["App"]["GetLoginURL"]();
}

export function GetWebsiteURL() {
  return window["go"]["main"]["App"]["GetWebsiteURL"]();
}

export function TryAuthenticateFromWebview() {
  return window["go"]["main"]["App"]["TryAuthenticateFromWebview"]();
}

export function SubmitWebviewCookies(arg1) {
  return window["go"]["main"]["App"]["SubmitWebviewCookies"](arg1);
}

export function UpdateConfig(arg1) {
  return window["go"]["main"]["App"]["UpdateConfig"](arg1);
}

export function GetTimerState() {
  return window["go"]["main"]["App"]["GetTimerState"]();
}

export function GetCurrentUser() {
  return window["go"]["main"]["App"]["GetCurrentUser"]();
}

export function GetWorkspaces() {
  return window["go"]["main"]["App"]["GetWorkspaces"]();
}

export function GetCurrentWorkspace() {
  return window["go"]["main"]["App"]["GetCurrentWorkspace"]();
}

export function SearchIssues(arg1) {
  return window["go"]["main"]["App"]["SearchIssues"](arg1);
}

export function GetMyIssues(arg1) {
  return window["go"]["main"]["App"]["GetMyIssues"](arg1);
}

export function GetFilterOptions() {
  return window["go"]["main"]["App"]["GetFilterOptions"]();
}

export function GetIssueTotalTime(arg1, arg2) {
  return window["go"]["main"]["App"]["GetIssueTotalTime"](arg1, arg2);
}

export function StartTracking(arg1, arg2) {
  return window["go"]["main"]["App"]["StartTracking"](arg1, arg2);
}

export function StartTrackingIssue(arg1) {
  return window["go"]["main"]["App"]["StartTrackingIssue"](arg1);
}

export function StopTracking() {
  return window["go"]["main"]["App"]["StopTracking"]();
}
