// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window["go"]["main"]["App"]["GetConfig"]();
}

export function UpdateConfig(arg1) {
  return window["go"]["main"]["App"]["UpdateConfig"](arg1);
}

export function GetTimerState() {
  return window["go"]["main"]["App"]["GetTimerState"]();
}

export function GetCurrentUser() {
  return window["go"]["main"]["App"]["GetCurrentUser"]();
}

export function GetWorkspaces() {
  return window["go"]["main"]["App"]["GetWorkspaces"]();
}

export function GetCurrentWorkspace() {
  return window["go"]["main"]["App"]["GetCurrentWorkspace"]();
}

export function SearchIssues(arg1) {
  return window["go"]["main"]["App"]["SearchIssues"](arg1);
}

export function StartTracking(arg1, arg2) {
  return window["go"]["main"]["App"]["StartTracking"](arg1, arg2);
}

export function StartTrackingIssue(arg1) {
  return window["go"]["main"]["App"]["StartTrackingIssue"](arg1);
}

export function StopTracking() {
  return window["go"]["main"]["App"]["StopTracking"]();
}
