// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig(): Promise<config.Config>;

export function GetAuthState(): Promise<main.AuthState>;

export function IsAuthenticated(): Promise<boolean>;

export function OpenLogin(): Promise<void>;

export function GetLoginURL(): Promise<string>;

export function TryAuthenticateFromWebview(): Promise<void>;

export function SubmitWebviewCookies(arg1: string): Promise<void>;

export function UpdateConfig(arg1: config.Config): Promise<void>;

export function GetTimerState(): Promise<timer.State>;

export function GetCurrentUser(): Promise<models.User>;

export function GetWorkspaces(): Promise<Array<models.Workspace>>;

export function GetCurrentWorkspace(): Promise<models.Workspace>;

export function SearchIssues(arg1: string): Promise<Array<models.Issue>>;

export function StartTracking(arg1: string, arg2: string): Promise<void>;

export function StartTrackingIssue(arg1: models.Issue): Promise<void>;

export function StopTracking(): Promise<void>;

export namespace main {
  export class AuthState {
    status: string;
    login_url: string;
    plane_url: string;
    user_email?: string;
  }
}

export namespace config {
  export class Config {
    plane_url: string;
    start_minimized: boolean;
    notification_sound: boolean;
    long_session_alert_minutes: number;
    last_workspace: string;
    sync_interval_minutes: number;
  }
}

export namespace timer {
  export class State {
    worklog_id: string;
    issue_id: string;
    issue_title: string;
    project_id: string;
    start_time: string;
    elapsed_seconds: number;
    is_active: boolean;
  }
}

export namespace models {
  export class User {
    id: string;
    email: string;
    display_name: string;
    first_name: string;
    last_name: string;
    avatar: string;
  }

  export class Workspace {
    id: string;
    name: string;
    slug: string;
    logo: string;
  }

  export class Issue {
    id: string;
    name: string;
    project_id: string;
    sequence_id: number;
    state: string;
    priority: string;
    project__identifier: string;
    workspace__slug: string;
    state_detail?: State;
  }

  export class State {
    id: string;
    name: string;
    color: string;
    group: string;
  }
}
